# Generated by Django 5.2.15 on 2026-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologia', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
